name: Build V8.NET 

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  V8_OBJ_ZIP: v8-out-PLATFORM.zip
  V8_INCLUDE_ZIP: include.zip 
  V8_BUILD_URL: https://github.com/gregolsky/v8-monolith-builds/releases/download/v9.9.115.9/
  BOOST_BEAST_URL: https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.tar.bz2

jobs:
  build_v8netproxy_linux_x64:
    name: Build for V8.NET Proxy for ${{ matrix.config.platform }} 
    runs-on: ${{ matrix.config.os }} 
    strategy:
      matrix:
        config:

          - os: ubuntu-latest
            name: linux
            arch: x64
            platform: linux-x64
            v8_lib_name: libv8_monolith.a
          
          # - os: windows-2019
          #   name: windows
          #   arch: x64
          #   platform: windows-x64
          #   v8_lib_name: v8_monolith.lib

    steps:
      - name: Clone repository
        uses: actions/checkout@master
        with:
          path: v8dotnet

      - name: Install depot tools
        shell: pwsh
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$pwd/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Download pre-built V8 library
        shell: bash
        run: |
          export PLATFORM="${{ matrix.config.platform }}" 
          wget -O v8.zip "${V8_BUILD_URL}${V8_OBJ_ZIP/PLATFORM/$PLATFORM}"
          wget -O v8-include.zip "${V8_BUILD_URL}${V8_INCLUDE_ZIP}"
          mkdir v8
          unzip -d v8 v8.zip
          unzip -d v8 v8-include.zip
          chmod -R 777 v8
          ls -R v8
      
      - name: Download BOOST Beast
        shell: bash
        run: |
          wget -O "boost.tar.bz2" "$BOOST_BEAST_URL"
          mkdir boost
          tar xvjf boost.tar.bz2 --strip-components 1 -C boost
          ls boost

      - name: Build
        shell: pwsh
        working-directory: v8dotnet
        run: |
          $env:V8_SRC = $(Get-Item ../v8).FullName
          $env:BOOST_SRC = $(Get-Item ../boost).FullName
          Write-Host "V8_SRC: $($env:V8_SRC)"
          Write-Host "BOOST_SRC: $($env:BOOST_SRC)"
          .\build.ps1 -Target "${{ matrix.config.platform }}"
